using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using assignment_sql_81clafra.Data;
using assignment_sql_81clafra.Models;

namespace assignment_sql_81clafra.Services
{
    // Code skeleton from https://github.com/Campus-Molndal-CLO25/Studiematerial/blob/main/2_databases/assignment/part_1/monster_tracker.md
    public class MonsterTrackerFacade
    {
        private MonsterRepository _monsterRepo;
        private LocationRepository _locationRepo;
        private HunterRepository _hunterRepo;
        private ObservationRepository _observationRepo;

        public MonsterTrackerFacade()
        {
            // Generated by by TabbyML/Qwen2.5-Coder-7B-Instruct
            _monsterRepo = new MonsterRepository();
            _locationRepo = new LocationRepository();
            _hunterRepo = new HunterRepository();
            _observationRepo = new ObservationRepository();
        }

        // Enkla operationer som delegerar till repositories
        public void CreateDatabase()
        {
            DatabaseCreation databaseCreationObject = new DatabaseCreation(); // With help from Perplexity, https://www.perplexity.ai/search/can-you-help-me-with-this-erro-1Vj.QVQzSbOfN8bbixFCdg#0
            databaseCreationObject.CreateDatabase();
        }

        public void AddMonster(string name, string type, string dangerLevel)
        {
            var monster = new Monster { Name = name, Type = type, DangerLevel = dangerLevel };
            _monsterRepo.CreateMonster(monster);
        }

        public List<Monster> GetAllMonsters()
        {
            return _monsterRepo.ReadAllMonsters();
        }

        public void UpdateMonster(int idToUpdate, string? newName, string? newType, string? newDangerLevel)
        {
            var monsterToUpdate = new Monster { Id = idToUpdate, Name = newName, Type = newType, DangerLevel = newDangerLevel };
            _monsterRepo.UpdateMonster(monsterToUpdate);
        }

        public void DeleteMonster(int idToDelete)
        {
            var monsterToDelete = new Monster { Id = idToDelete };
            _monsterRepo.DeleteMonster(monsterToDelete);
        }
        
        public void AddHunter(string name, string experienceLevel)
        {
            var hunter = new Hunter { Name = name, ExperienceLevel = experienceLevel };
            _hunterRepo.CreateHunter(hunter);
        }

        public List<Hunter> GetAllHunters()
        {
            return _hunterRepo.ReadAllHunters();
        }

        public void UpdateHunter(int idToUpdate, string? newName, string? newExperienceLevel)
        {
            var hunterToUpdate = new Hunter { Id = idToUpdate, Name = newName, ExperienceLevel = newExperienceLevel };
            _hunterRepo.UpdateHunter(hunterToUpdate);
        }

        public void DeleteHunter(int idToDelete)
        {
            var hunterToDelete = new Hunter { Id = idToDelete};
            _hunterRepo.DeleteHunter(hunterToDelete);
        }


        // Mer komplexa operationer som kombinerar flera repositories
        // public List<Observation> GetObservationsByMonsterType(string type)
        // {
        // TODO: Hämta monster av typ, sedan deras observationer
        // Detta kräver anrop till både MonsterRepository och ObservationRepository
        // }
    }
}