using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Linq;
using System.Threading.Tasks;

namespace assignment_sql_81clafra.Data
{
    public class DatabaseConnection
    {
        // Generated by TabbyML/Qwen2.5-Coder-7B-Instruct
        public static SQLiteConnection GetConnection()
        {
            var connection = new SQLiteConnection("Data Source=MonsterTracker.db;Version=3;");
            connection.Open();
            return connection;
        }
    }
}