using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Linq;
using System.Threading.Tasks;

namespace assignment_sql_81clafra.Data
{
    public class DatabaseConnection
    {
        // Generated by TabbyML/Qwen2.5-Coder-7B-Instruct
        public static SQLiteConnection GetConnection()
        {
            var connection = new SQLiteConnection("Data Source=MonsterTracker.db;Version=3;");
            connection.Open();

            // Aktivera foreign keys
            // Implementation from https://campusmolndaleducation.github.io/csharp_cmyh/C-Sharp/databases/ado_net_sqlite/#best-practices
            using var sqlCommand = new SQLiteCommand("PRAGMA foreign_keys = ON", connection);
            sqlCommand.ExecuteNonQuery();

            return connection;
        }
    }
}