using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace assignment_sql_81clafra.Models
{
    public class Monster
    {
        // Generated by Visual Studio Code
        public Monster(int id, string name, string type, string dangerLevel)
        {
            Id = id;
            Name = name;
            Type = type;
            DangerLevel = dangerLevel;
        }

        // Generated with help from TabbyML/Qwen2.5-Coder-7B-Instruct
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string DangerLevel { get; set; }

    }
}